In [6]:
import torch

In [7]:
x = torch.empty(1) # 1D
print(x)

tensor([1.4457e-34])


In [8]:
x = torch.empty(3) # 1D
print(x)

tensor([1.4462e-34, 0.0000e+00, 1.4460e-34])


In [9]:
x = torch.empty(3,3) # 2D
print(x)

tensor([[1.8658e-35, 0.0000e+00, 1.4465e-34],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [13]:
x = torch.empty(2,3,2)
print(x)

tensor([[[7.2429e-10, 4.5772e-41],
         [1.4465e-34, 0.0000e+00],
         [9.1477e-41, 0.0000e+00]],

        [[1.1210e-44, 0.0000e+00],
         [9.6299e-35, 0.0000e+00],
         [7.5805e-10, 4.5772e-41]]])


In [15]:
x = torch.rand(3,3)
print(x)

tensor([[0.9145, 0.0509, 0.9234],
        [0.0435, 0.7671, 0.3028],
        [0.1026, 0.8234, 0.4289]])


In [16]:
x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
x = torch.ones(3, 3, dtype=torch.int16)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [22]:
A = [2.5, 0.1] 
x = torch.tensor(A)
print(x)

tensor([2.5000, 0.1000])


In [25]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print("\n")
print(y)

tensor([[0.8021, 0.2009],
        [0.4734, 0.9017]])


tensor([[0.2187, 0.3712],
        [0.5422, 0.7293]])


In [27]:
z = x*y
print(z)

tensor([[0.1754, 0.0746],
        [0.2567, 0.6577]])


In [29]:
z = torch.mul(x, y) # element wise
print(z)

tensor([[0.1754, 0.0746],
        [0.2567, 0.6577]])


In [30]:
z = torch.add(x, y) # penjumlahan
print(z)

tensor([[1.0208, 0.5720],
        [1.0156, 1.6311]])


In [31]:
z = torch.sub(x, y) # pengurangan
print(z)

tensor([[ 0.5834, -0.1703],
        [-0.0687,  0.1724]])


In [33]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9200, 0.2644, 0.5715],
        [0.6663, 0.2822, 0.2916],
        [0.5810, 0.0037, 0.1849],
        [0.1414, 0.6081, 0.6746],
        [0.3613, 0.8270, 0.4768]])


In [35]:
x[:, 0] # 1st column all rows

tensor([0.9200, 0.6663, 0.5810, 0.1414, 0.3613])

In [36]:
x[0,:] # 1st row all columns

tensor([0.9200, 0.2644, 0.5715])

In [37]:
x[:2, :]

tensor([[0.9200, 0.2644, 0.5715],
        [0.6663, 0.2822, 0.2916]])

In [38]:
x[0,0]

tensor(0.9200)

In [39]:
x[0,0].item() # just return the value

0.9199695587158203

In [41]:
x = torch.rand(4,4)
print(x)

tensor([[0.8358, 0.2653, 0.3647, 0.3145],
        [0.8106, 0.0989, 0.5345, 0.1674],
        [0.4485, 0.4558, 0.6466, 0.6909],
        [0.4544, 0.3330, 0.0094, 0.3148]])


In [44]:
y = x.view(16) # flatten

In [45]:
y

tensor([0.8358, 0.2653, 0.3647, 0.3145, 0.8106, 0.0989, 0.5345, 0.1674, 0.4485,
        0.4558, 0.6466, 0.6909, 0.4544, 0.3330, 0.0094, 0.3148])

In [46]:
y = x.view(2, 8) #2 x 8

In [47]:
y

tensor([[0.8358, 0.2653, 0.3647, 0.3145, 0.8106, 0.0989, 0.5345, 0.1674],
        [0.4485, 0.4558, 0.6466, 0.6909, 0.4544, 0.3330, 0.0094, 0.3148]])

In [49]:
y = x.view(-1,8) # just want 8 columns
y

tensor([[0.8358, 0.2653, 0.3647, 0.3145, 0.8106, 0.0989, 0.5345, 0.1674],
        [0.4485, 0.4558, 0.6466, 0.6909, 0.4544, 0.3330, 0.0094, 0.3148]])