In [14]:
import numpy as np
import torch

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
a_np = np.array([.5, .4, 2])
print(a_np)

[0.5 0.4 2. ]


In [17]:
b_np = torch.tensor(a_np) # array to tensor
print(b_np)

tensor([0.5000, 0.4000, 2.0000], dtype=torch.float64)


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [13]:
type(b)

numpy.ndarray

In [19]:
type(a)

torch.Tensor

In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    print(x)
    # z = x.numpy() # it didn't work

In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    print(x)
    x = x.to("cpu")
    print(x)
    z = x.numpy()
    print(z)